push_pypi:
    stage: deploy
    image: python:3.6.5
    script:
        - pip install --upgrade pip
        - pip install twine setuptools
        - rm -rf dist
        - echo "[distutils]" >> ~/.pypirc
        - echo "index-servers =" >> ~/.pypirc
        - echo "    pypi" >> ~/.pypirc
        - echo "" >> ~/.pypirc
        - echo "[pypi]" >> ~/.pypirc
        - echo "${PYPI_REPO}" >> ~/.pypirc
        - echo "${PYPI_USER}" >> ~/.pypirc
        - echo "${PYPI_PASSWORD}" >> ~/.pypirc
        - python setup.py sdist bdist_wheel
        - twine upload -r pypi dist/*.whl
push_github:
    stage: deploy
    script:
        - wget -q https://gitlab.com/ludeeus/toolbox/raw/master/CI-Scripts/push_to_public_repo/init.sh
        - wget -q https://gitlab.com/ludeeus/toolbox/raw/master/CI-Scripts/push_to_public_repo/push.sh
        - bash init.sh github pip-packages "" /pycfdns
        - bash push.sh Europe/Oslo